# Generated by Django 5.0.6 on 2024-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffusers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='position',
        ),
        migrations.AddField(
            model_name='staffuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
